/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedCoursesManageRouteImport } from './routes/_authenticated/courses.manage'
import { Route as AuthenticatedLessonsSlugRouteImport } from './routes/_authenticated/lessons.$slug'
import { Route as AuthenticatedMocksIndexRouteImport } from './routes/_authenticated/mocks.index'
import { Route as AuthenticatedMocksIdRouteImport } from './routes/_authenticated/mocks.$id'
import { Route as AuthenticatedMocksManageRouteImport } from './routes/_authenticated/mocks.manage'
import { Route as AuthenticatedPracticeIndexRouteImport } from './routes/_authenticated/practice.index'
import { Route as AuthenticatedPracticeManageRouteImport } from './routes/_authenticated/practice.manage'
import { Route as AuthenticatedReadingIndexRouteImport } from './routes/_authenticated/reading.index'
import { Route as AuthenticatedReadingSlugRouteImport } from './routes/_authenticated/reading.$slug'
import { Route as AuthenticatedReadingManageRouteImport } from './routes/_authenticated/reading.manage'
import { Route as AuthenticatedVocabIndexRouteImport } from './routes/_authenticated/vocab.index'
import { Route as AuthenticatedVocabManageRouteImport } from './routes/_authenticated/vocab.manage'
import { Route as AuthenticatedVocabStudyRouteImport } from './routes/_authenticated/vocab.study'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCoursesManageRoute =
  AuthenticatedCoursesManageRouteImport.update({
    id: '/courses/manage',
    path: '/courses/manage',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLessonsSlugRoute =
  AuthenticatedLessonsSlugRouteImport.update({
    id: '/lessons/$slug',
    path: '/lessons/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMocksIndexRoute = AuthenticatedMocksIndexRouteImport.update({
  id: '/mocks/',
  path: '/mocks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMocksIdRoute = AuthenticatedMocksIdRouteImport.update({
  id: '/mocks/$id',
  path: '/mocks/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMocksManageRoute =
  AuthenticatedMocksManageRouteImport.update({
    id: '/mocks/manage',
    path: '/mocks/manage',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPracticeIndexRoute =
  AuthenticatedPracticeIndexRouteImport.update({
    id: '/practice/',
    path: '/practice/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPracticeManageRoute =
  AuthenticatedPracticeManageRouteImport.update({
    id: '/practice/manage',
    path: '/practice/manage',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReadingIndexRoute =
  AuthenticatedReadingIndexRouteImport.update({
    id: '/reading/',
    path: '/reading/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReadingSlugRoute =
  AuthenticatedReadingSlugRouteImport.update({
    id: '/reading/$slug',
    path: '/reading/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReadingManageRoute =
  AuthenticatedReadingManageRouteImport.update({
    id: '/reading/manage',
    path: '/reading/manage',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVocabIndexRoute = AuthenticatedVocabIndexRouteImport.update({
  id: '/vocab/',
  path: '/vocab/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVocabManageRoute =
  AuthenticatedVocabManageRouteImport.update({
    id: '/vocab/manage',
    path: '/vocab/manage',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVocabStudyRoute = AuthenticatedVocabStudyRouteImport.update({
  id: '/vocab/study',
  path: '/vocab/study',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/courses/manage': typeof AuthenticatedCoursesManageRoute
  '/lessons/$slug': typeof AuthenticatedLessonsSlugRoute
  '/mocks/$id': typeof AuthenticatedMocksIdRoute
  '/mocks/manage': typeof AuthenticatedMocksManageRoute
  '/practice/manage': typeof AuthenticatedPracticeManageRoute
  '/reading/$slug': typeof AuthenticatedReadingSlugRoute
  '/reading/manage': typeof AuthenticatedReadingManageRoute
  '/vocab/manage': typeof AuthenticatedVocabManageRoute
  '/vocab/study': typeof AuthenticatedVocabStudyRoute
  '/mocks/': typeof AuthenticatedMocksIndexRoute
  '/practice/': typeof AuthenticatedPracticeIndexRoute
  '/reading/': typeof AuthenticatedReadingIndexRoute
  '/vocab/': typeof AuthenticatedVocabIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/courses/manage': typeof AuthenticatedCoursesManageRoute
  '/lessons/$slug': typeof AuthenticatedLessonsSlugRoute
  '/mocks/$id': typeof AuthenticatedMocksIdRoute
  '/mocks/manage': typeof AuthenticatedMocksManageRoute
  '/practice/manage': typeof AuthenticatedPracticeManageRoute
  '/reading/$slug': typeof AuthenticatedReadingSlugRoute
  '/reading/manage': typeof AuthenticatedReadingManageRoute
  '/vocab/manage': typeof AuthenticatedVocabManageRoute
  '/vocab/study': typeof AuthenticatedVocabStudyRoute
  '/mocks': typeof AuthenticatedMocksIndexRoute
  '/practice': typeof AuthenticatedPracticeIndexRoute
  '/reading': typeof AuthenticatedReadingIndexRoute
  '/vocab': typeof AuthenticatedVocabIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/courses/manage': typeof AuthenticatedCoursesManageRoute
  '/_authenticated/lessons/$slug': typeof AuthenticatedLessonsSlugRoute
  '/_authenticated/mocks/$id': typeof AuthenticatedMocksIdRoute
  '/_authenticated/mocks/manage': typeof AuthenticatedMocksManageRoute
  '/_authenticated/practice/manage': typeof AuthenticatedPracticeManageRoute
  '/_authenticated/reading/$slug': typeof AuthenticatedReadingSlugRoute
  '/_authenticated/reading/manage': typeof AuthenticatedReadingManageRoute
  '/_authenticated/vocab/manage': typeof AuthenticatedVocabManageRoute
  '/_authenticated/vocab/study': typeof AuthenticatedVocabStudyRoute
  '/_authenticated/mocks/': typeof AuthenticatedMocksIndexRoute
  '/_authenticated/practice/': typeof AuthenticatedPracticeIndexRoute
  '/_authenticated/reading/': typeof AuthenticatedReadingIndexRoute
  '/_authenticated/vocab/': typeof AuthenticatedVocabIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/dashboard'
    | '/auth/callback'
    | '/courses/manage'
    | '/lessons/$slug'
    | '/mocks/$id'
    | '/mocks/manage'
    | '/practice/manage'
    | '/reading/$slug'
    | '/reading/manage'
    | '/vocab/manage'
    | '/vocab/study'
    | '/mocks/'
    | '/practice/'
    | '/reading/'
    | '/vocab/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/dashboard'
    | '/auth/callback'
    | '/courses/manage'
    | '/lessons/$slug'
    | '/mocks/$id'
    | '/mocks/manage'
    | '/practice/manage'
    | '/reading/$slug'
    | '/reading/manage'
    | '/vocab/manage'
    | '/vocab/study'
    | '/mocks'
    | '/practice'
    | '/reading'
    | '/vocab'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/dashboard'
    | '/auth/callback'
    | '/_authenticated/courses/manage'
    | '/_authenticated/lessons/$slug'
    | '/_authenticated/mocks/$id'
    | '/_authenticated/mocks/manage'
    | '/_authenticated/practice/manage'
    | '/_authenticated/reading/$slug'
    | '/_authenticated/reading/manage'
    | '/_authenticated/vocab/manage'
    | '/_authenticated/vocab/study'
    | '/_authenticated/mocks/'
    | '/_authenticated/practice/'
    | '/_authenticated/reading/'
    | '/_authenticated/vocab/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/courses/manage': {
      id: '/_authenticated/courses/manage'
      path: '/courses/manage'
      fullPath: '/courses/manage'
      preLoaderRoute: typeof AuthenticatedCoursesManageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lessons/$slug': {
      id: '/_authenticated/lessons/$slug'
      path: '/lessons/$slug'
      fullPath: '/lessons/$slug'
      preLoaderRoute: typeof AuthenticatedLessonsSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mocks/': {
      id: '/_authenticated/mocks/'
      path: '/mocks'
      fullPath: '/mocks/'
      preLoaderRoute: typeof AuthenticatedMocksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mocks/$id': {
      id: '/_authenticated/mocks/$id'
      path: '/mocks/$id'
      fullPath: '/mocks/$id'
      preLoaderRoute: typeof AuthenticatedMocksIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mocks/manage': {
      id: '/_authenticated/mocks/manage'
      path: '/mocks/manage'
      fullPath: '/mocks/manage'
      preLoaderRoute: typeof AuthenticatedMocksManageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/practice/': {
      id: '/_authenticated/practice/'
      path: '/practice'
      fullPath: '/practice/'
      preLoaderRoute: typeof AuthenticatedPracticeIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/practice/manage': {
      id: '/_authenticated/practice/manage'
      path: '/practice/manage'
      fullPath: '/practice/manage'
      preLoaderRoute: typeof AuthenticatedPracticeManageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reading/': {
      id: '/_authenticated/reading/'
      path: '/reading'
      fullPath: '/reading/'
      preLoaderRoute: typeof AuthenticatedReadingIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reading/$slug': {
      id: '/_authenticated/reading/$slug'
      path: '/reading/$slug'
      fullPath: '/reading/$slug'
      preLoaderRoute: typeof AuthenticatedReadingSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reading/manage': {
      id: '/_authenticated/reading/manage'
      path: '/reading/manage'
      fullPath: '/reading/manage'
      preLoaderRoute: typeof AuthenticatedReadingManageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vocab/': {
      id: '/_authenticated/vocab/'
      path: '/vocab'
      fullPath: '/vocab/'
      preLoaderRoute: typeof AuthenticatedVocabIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vocab/manage': {
      id: '/_authenticated/vocab/manage'
      path: '/vocab/manage'
      fullPath: '/vocab/manage'
      preLoaderRoute: typeof AuthenticatedVocabManageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vocab/study': {
      id: '/_authenticated/vocab/study'
      path: '/vocab/study'
      fullPath: '/vocab/study'
      preLoaderRoute: typeof AuthenticatedVocabStudyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedCoursesManageRoute: typeof AuthenticatedCoursesManageRoute
  AuthenticatedLessonsSlugRoute: typeof AuthenticatedLessonsSlugRoute
  AuthenticatedMocksIdRoute: typeof AuthenticatedMocksIdRoute
  AuthenticatedMocksManageRoute: typeof AuthenticatedMocksManageRoute
  AuthenticatedPracticeManageRoute: typeof AuthenticatedPracticeManageRoute
  AuthenticatedReadingSlugRoute: typeof AuthenticatedReadingSlugRoute
  AuthenticatedReadingManageRoute: typeof AuthenticatedReadingManageRoute
  AuthenticatedVocabManageRoute: typeof AuthenticatedVocabManageRoute
  AuthenticatedVocabStudyRoute: typeof AuthenticatedVocabStudyRoute
  AuthenticatedMocksIndexRoute: typeof AuthenticatedMocksIndexRoute
  AuthenticatedPracticeIndexRoute: typeof AuthenticatedPracticeIndexRoute
  AuthenticatedReadingIndexRoute: typeof AuthenticatedReadingIndexRoute
  AuthenticatedVocabIndexRoute: typeof AuthenticatedVocabIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedCoursesManageRoute: AuthenticatedCoursesManageRoute,
  AuthenticatedLessonsSlugRoute: AuthenticatedLessonsSlugRoute,
  AuthenticatedMocksIdRoute: AuthenticatedMocksIdRoute,
  AuthenticatedMocksManageRoute: AuthenticatedMocksManageRoute,
  AuthenticatedPracticeManageRoute: AuthenticatedPracticeManageRoute,
  AuthenticatedReadingSlugRoute: AuthenticatedReadingSlugRoute,
  AuthenticatedReadingManageRoute: AuthenticatedReadingManageRoute,
  AuthenticatedVocabManageRoute: AuthenticatedVocabManageRoute,
  AuthenticatedVocabStudyRoute: AuthenticatedVocabStudyRoute,
  AuthenticatedMocksIndexRoute: AuthenticatedMocksIndexRoute,
  AuthenticatedPracticeIndexRoute: AuthenticatedPracticeIndexRoute,
  AuthenticatedReadingIndexRoute: AuthenticatedReadingIndexRoute,
  AuthenticatedVocabIndexRoute: AuthenticatedVocabIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
